### ISSUE TITLE
Should show OUTPUT tab as soon as there's new content available

### ISSUE THREAD

**Issue by adietish** [redhat-developer/vscode-adapters#304]
steps:
1. ASSERT: have a server
1. EXEC: add a deployment
1. ASSERT: server turns to ```(synchronized)``` once the copying is done
1. ASSERT: deployment is not picked up by the server yet.

Result: 
You now have wait for the server to pick up and activating the deployment. You see this to happen in the OUTPUT channel. It would help if vscode was showing the output channel as soon as there's new content available.

**Comment by lstocchi** [comment]
@adietish Because there are several issues related to the output tab (like #231 ) i was thinking for a solution to solve all of them. In some cases there will be the need to only display the error messages, other cases where it's more useful to display all logs. 
Unfortunately there is no filtering function a user can use in the output tab so my idea is:

1) create a new setting where a user can set up the verbosity of logs displayed (like log4j) - 

- ANY
- INFO
- ERROR

and we filter logs based on that setting

2) create 2 different channels per server in which the first should contain all logs and the second only the error messages and show them based on the command executed by the user

I vote the first

**Comment by adietish** [comment]
we already have such an option in the preferences:
![image](https://user-images.githubusercontent.com/25126/57386655-16f9ce00-71b5-11e9-99d2-ba8717eadf24.png)
The only thing is that it should be **true** by default.
