### ISSUE TITLE
Failed to add server

### ISSUE THREAD

**Issue by lkachun9129** [redhat-developer/vscode-adapters#316]
Output from console:  
![image](https://user-images.githubusercontent.com/6640910/57232680-af763e00-704f-11e9-9330-9ce7df7535b2.png)

Is the attribute `serverType` missing from the request?

```java
private CreateServerResponse createServerSync(ServerAttributes attr) {
	if( attr == null || isEmpty(attr.getId()) || isEmpty(attr.getServerType())) {
		Status s = invalidParameterStatus();
		return new CreateServerResponse(s, null);
	}
		
	String serverType = attr.getServerType();
	String id = attr.getId();
	Map<String, Object> attributes = attr.getAttributes();
		
	CreateServerResponse ret = managementModel.getServerModel().createServer(serverType, id, attributes);
	return ret;
}
```

Reference: https://github.com/redhat-developer/rsp-server/blob/master/framework/bundles/org.jboss.tools.rsp.server/src/main/java/org/jboss/tools/rsp/server/ServerManagementServerImpl.java#L312

Remarks: I was trying to add a jboss server in WSL using `Visual Studio Code Remote - WSL`

**Comment by robstryker** [comment]
Thanks for this issue. Yes, it seems you are right, there's a bug here. 

First, the server bean search is missing a line in the return:
{
  "jsonrpc": "2.0",
  "id": "4",
  "result": [
    {
      "typeCategory": "AS",
      "specificType": "AS",
      etc etc etc
      "serverAdapterTypeId": "org.jboss.ide.eclipse.as.71"   // THIS LINE HERE, MISSING
    }
  ]
}
Since the server bean returns without an appropriate server type, it seems vscode-adapters then attempts to 
just create a server despite not knowing its type.  

The root cause on the server side appears to be in ServerBeanTypeAS7, where I check that a version string match exactly 7.1, 7.0, etc, when really I should be using startsWith instead. 

But, the vscode-adapters code also should not be trying to make a server if it doesn't know the type somehow.

**Comment by robstryker** [comment]
@adietish @lstocchi   Can one of you guys add protections on the vscode side to make sure if a search of server beans comes up with no server type, that it not be used to create a server?
